Update study.yml

diff --git a/.github/workflows/study.yml b/.github/workflows/study.yml
--- a/.github/workflows/study.yml
+++ b/.github/workflows/study.yml
@@ -44,8 +44,56 @@ jobs:
           fi
           if [ $CURRENT_UPSTREAN -eq blue ]; then
             echo "CURRENT_IP=${{ secrets.BLUE_IP }}" >> $GITHUB_ENV
-          fi
-          if [ $CURRENT_UPSTREAN -eq green ]; then
+            echo "STOPPED_IP=${{ secrets.GREEN_IP }}" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+          elif [ $CURRENT_UPSTREAN -eq green ]; then
             echo "CURRENT_IP=${{ secrets.GREEN_IP }}" >> $GITHUB_ENV
+            echo "STOPPED_IP=${{ secrets.BLUE_IP }}" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+          else
+            echo "error"
+            exit 1
           fi
-          
+      - name: Docker compose
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ env.STOPPED_IP }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script_stop: true
+          script:
+            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/server:latest
+            docker-compose up -d
+      - name: Check deploy server URL PORT 8080
+        uses: jtalk/url-health-check-action@v3
+        with:
+          url: http://${{ env.STOPPED_IP }}/8080/env
+          max-attempts: 3
+          retry-delay: 10s
+      - name: Check deploy server URL PORT 8081
+        uses: jtalk/url-health-check-action@v3
+        with:
+          url: http://${{ env.STOPPED_IP }}/8081/env
+          max-attempts: 3
+          retry-delay: 10s
+      - name: Change nginx upstream
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ env.NGINX_IP }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script_stop: true
+          script: 
+            docker exec -i nginxserver bash -c 'echo "set \$server_env ${{ env.TARGET_UPSTREAM }}"; >> /etc/nginx/conf.d/server-env.inc && service nginx reload'
+      - name: Stop Current server
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ env.CURRENT_IP }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script_stop: true
+          script:
+            docker stop prod1
+            docker stop prod2
+            docker rm prod1
+            docker rm prod2
