Update study.yml

diff --git a/.github/workflows/study.yml b/.github/workflows/study.yml
--- a/.github/workflows/study.yml
+++ b/.github/workflows/study.yml
@@ -37,28 +37,30 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     steps:
-      # - name: Set target IP
-      #   run: |
-      #     STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.NGINX_IP }}/env")
-      #     echo $STATUS
-      #     if [ $STATUS = 404 ]; then
-      #       CURRENT_UPSTREAM=blue
-      #     else
-      #       CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.NGINX_IP }}/env")
-      #     fi
-      #     echo $CURRENT_UPSTREAM
-      #     if [ $CURRENT_UPSTREAM = blue ]; then
-      #       echo "CURRENT_IP=${{ secrets.BLUE_IP }}" >> $GITHUB_ENV
-      #       echo "STOPPED_IP=${{ secrets.GREEN_IP }}" >> $GITHUB_ENV
-      #       echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
-      #     elif [ $CURRENT_UPSTREAM = green ]; then
-      #       echo "CURRENT_IP=${{ secrets.GREEN_IP }}" >> $GITHUB_ENV
-      #       echo "STOPPED_IP=${{ secrets.BLUE_IP }}" >> $GITHUB_ENV
-      #       echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
-      #     else
-      #       echo "error"
-      #       exit 1
-      #     fi
+      - name: Set target IP
+        run: |
+          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.NGINX_IP }}/env")
+          echo $STATUS
+          if [ $STATUS = 404 ]; then
+            CURRENT_UPSTREAM=blue
+          else [ $STATUS = 502 ]; then
+            CURRENT_UPSTREAM=blue
+          else
+            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.NGINX_IP }}/env")
+          fi
+          echo $CURRENT_UPSTREAM
+          if [ $CURRENT_UPSTREAM = blue ]; then
+            echo "CURRENT_IP=${{ secrets.BLUE_IP }}" >> $GITHUB_ENV
+            echo "STOPPED_IP=${{ secrets.GREEN_IP }}" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+          elif [ $CURRENT_UPSTREAM = green ]; then
+            echo "CURRENT_IP=${{ secrets.GREEN_IP }}" >> $GITHUB_ENV
+            echo "STOPPED_IP=${{ secrets.BLUE_IP }}" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+          else
+            echo "error"
+            exit 1
+          fi
       - name: Docker pull
         uses: appleboy/ssh-action@master
         with:
